[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventzilla = { path = "../../eventzilla" }

axum = "0.7.4"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.35.1", features = ["net", "rt-multi-thread"] }
